version: '3.4'
services:
    api-gateway:
        container_name: API_GATEWAY
        build: https://github.com/MilaGuilherme/api-gateway-aws.git
        ports:
            - "3000:3000"
    api-products:
        container_name: API_PRODUCTS
        build: https://github.com/MilaGuilherme/aws-products-api.git#main
        ports:
            - "3002:3002"
    api-sales:
        container_name: API_SALES
        build: https://github.com/MilaGuilherme/api_sales.git#main
        ports:
            - "3001:3001"